/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir.penjualan;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 62831
 */
public class kasir extends javax.swing.JFrame {

    /**
     * Creates new form kasir
     */
    public kasir() {
        initComponents();
    }
    
    public void reset() {
        brng.setSelectedIndex(0);
        jh.setText("");
        jb.setText("");
        jk.setText("");
        jmlb.setText("");
        hrg.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jk = new javax.swing.JTextField();
        jmlb = new javax.swing.JTextField();
        jh = new javax.swing.JTextField();
        jb = new javax.swing.JTextField();
        hrg = new javax.swing.JTextField();
        brng = new javax.swing.JComboBox<>();
        exit = new javax.swing.JButton();
        btl = new javax.swing.JButton();
        btn_byr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("KASIR TOKO KOSMETIK MRFW");

        jLabel2.setText("NAMA BARANG");

        jLabel3.setText("HARGA BARANG");

        jLabel4.setText("JUMLAH BELI");

        jLabel5.setText("JUMLAH HARGA");

        jLabel6.setText("JUMLAH BAYAR");

        jLabel7.setText("JUMLAH KEMBALIAN");

        jk.setEditable(false);

        jmlb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jmlbKeyReleased(evt);
            }
        });

        jh.setEditable(false);
        jh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhActionPerformed(evt);
            }
        });

        jb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbKeyReleased(evt);
            }
        });

        hrg.setEditable(false);

        brng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH BARANG", "LIPSTIK", "BEDAK", "TONER", "PONDATION", "MINYAK WANGI", "SABUN CUCI MUKA" }));
        brng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brngActionPerformed(evt);
            }
        });

        exit.setText("KELUAR");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        btl.setText("BATAL");
        btl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlActionPerformed(evt);
            }
        });

        btn_byr.setText("BAYAR");
        btn_byr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_byrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hrg, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jb, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(brng, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jh, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jmlb, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jk))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btn_byr)
                                    .addGap(18, 18, 18)
                                    .addComponent(btl)
                                    .addGap(18, 18, 18)
                                    .addComponent(exit))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(brng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jmlb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(btl)
                    .addComponent(btn_byr))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhActionPerformed

    private void brngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brngActionPerformed
        int pilih = brng.getSelectedIndex();
        if(pilih == 0) {
            hrg.setText("");
        } else if (pilih == 1) {
            hrg.setText("23000");
        } else if (pilih == 2) {
            hrg.setText("60000");
        } else if (pilih == 3) {
            hrg.setText("23000");
        } else if (pilih == 4) {
            hrg.setText("15000");
        } else if (pilih == 5) {
            hrg.setText("26000");
        } else if (pilih == 6) {
            hrg.setText("28000");
        } else {
            System.out.println("tidak valid!!");
        }
    }//GEN-LAST:event_brngActionPerformed

    private void jbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbKeyReleased
        int harga_barang = Integer.parseInt(hrg.getText());
        int jumlah_beli = Integer.parseInt(jb.getText());
        int total = harga_barang * jumlah_beli;
        jh.setText(String.valueOf(total));
    }//GEN-LAST:event_jbKeyReleased

    private void jmlbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmlbKeyReleased
        int jumlah_bayar = Integer.parseInt(jmlb.getText());
        int jumlah_harga = Integer.parseInt(jh.getText());
        int total = jumlah_bayar - jumlah_harga;
        jk.setText(String.valueOf(total));
    }//GEN-LAST:event_jmlbKeyReleased

    private void btn_byrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_byrActionPerformed
        JFrame frame = new JFrame();
        String tampil[] = {
           "--------- STRUK PEMBELANJAAN ANDA -------",
           "Nama Barang : "+brng.getSelectedItem().toString(),
            "Harga Barang : "+hrg.getText(),
            "Jumlah Beli : "+jb.getText(),
            "Jumlah Harga : "+jh.getText(),
            "Jumlah Bayar : "+jmlb.getText(),
            "Jumlah Kembalian : "+jk.getText(),
            "---------- Terimakasih ------------"
        };
        
        JOptionPane.showMessageDialog(frame, tampil);
        reset();
    }//GEN-LAST:event_btn_byrActionPerformed

    private void btlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlActionPerformed
        reset();
    }//GEN-LAST:event_btlActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brng;
    private javax.swing.JButton btl;
    private javax.swing.JButton btn_byr;
    private javax.swing.JButton exit;
    private javax.swing.JTextField hrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jb;
    private javax.swing.JTextField jh;
    private javax.swing.JTextField jk;
    private javax.swing.JTextField jmlb;
    // End of variables declaration//GEN-END:variables
}
